# Generated by Django 6.1 on 2026-08-26 12:43

import dashboard.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0017_alter_salesgoal_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyStrategicProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                (
                    "sector",
                    models.CharField(
                        choices=[
                            ("retail", "تجزئة"),
                            ("restaurant", "مطاعم"),
                            ("manufacturing", "تصنيع"),
                            ("services", "خدمات"),
                            ("ecommerce", "تجارة إلكترونية"),
                            ("other", "أخرى"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("micro", "متناهية الصغر (1-5)"),
                            ("small", "صغيرة (6-49)"),
                            ("medium", "متوسطة (50-249)"),
                            ("large", "كبيرة (250+)"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "growth_stage",
                    models.CharField(
                        choices=[
                            ("startup", "تأسيس / بداية"),
                            ("growth", "نمو وتوسع"),
                            ("mature", "استقرار وتشغيل"),
                            ("turnaround", "إعادة هيكلة / تخفيض تكاليف"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "strategic_priorities_ranking",
                    models.JSONField(
                        default=list,
                        validators=[dashboard.models.validate_strategic_priorities],
                    ),
                ),
                (
                    "risk_tolerance",
                    models.CharField(
                        choices=[
                            ("conservative", "محافظ (Conservative)"),
                            ("balanced", "متوازن (Balanced)"),
                            ("aggressive", "جريء (Aggressive)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "max_investment_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "cash_reserve_floor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("active_agents", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
