# Generated by Django 5.2.17 on 2026-09-20
#
# Scope: the archiving & document-management additions only. The unrelated
# "AlterField id -> AutoField" churn Django wanted to emit for every legacy
# model (pre-existing DEFAULT_AUTO_FIELD drift) is intentionally left out so
# this migration never rewrites existing primary keys.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0025_projectfile_document_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="projectfile",
            name="archive_status",
            field=models.CharField(
                choices=[
                    ("received", "مستلمة / Received"),
                    ("needs_review", "بانتظار مراجعة بشرية / Needs Human Review"),
                    ("verified", "موثّقة بشرياً / Human-Verified"),
                    ("archived", "مؤرشفة / Archived"),
                ],
                default="received",
                max_length=20,
                verbose_name="حالة الأرشفة / Archive Status",
            ),
        ),
        migrations.AddField(
            model_name="projectfile",
            name="archived_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="وقت الأرشفة / Archived At"
            ),
        ),
        migrations.AddField(
            model_name="projectfile",
            name="content_hash",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                verbose_name="بصمة السلامة (SHA-256) / Integrity Hash",
            ),
        ),
        migrations.AddField(
            model_name="projectfile",
            name="verified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="وقت المراجعة / Verified At"
            ),
        ),
        migrations.AddField(
            model_name="projectfile",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="روجع بواسطة / Verified By",
            ),
        ),
        migrations.CreateModel(
            name="DocumentAuditEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("received", "استلام / Received"),
                            ("validated", "تحقّق آلي / Validated"),
                            ("needs_review", "إحالة لمراجعة بشرية / Flagged for Review"),
                            ("human_verified", "مراجعة بشرية / Human-Verified"),
                            ("archived", "أرشفة / Archived"),
                            ("integrity_ok", "تأكيد سلامة / Integrity Confirmed"),
                            ("integrity_failed", "فشل تأكيد السلامة / Integrity Failed"),
                            ("report_issued", "إصدار تقرير / Report Issued"),
                        ],
                        max_length=30,
                        verbose_name="الإجراء / Action",
                    ),
                ),
                (
                    "detail",
                    models.TextField(
                        blank=True, default="", verbose_name="التفاصيل / Detail"
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="البصمة وقت الإجراء / Hash at Event",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="وقت الإجراء / At"
                    ),
                ),
                (
                    "project_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to="dashboard.projectfile",
                        verbose_name="المستند / Document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم / User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Audit Entry",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FinancialReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="عنوان التقرير / Title"
                    ),
                ),
                ("body", models.TextField(verbose_name="نص التقرير / Body")),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="بصمة السلامة / Integrity Hash",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("issued", "صادر / Issued"),
                            ("archived", "مؤرشف / Archived"),
                        ],
                        default="issued",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإصدار / Issued At"
                    ),
                ),
                (
                    "source_files",
                    models.ManyToManyField(
                        blank=True,
                        related_name="reports",
                        to="dashboard.projectfile",
                        verbose_name="المستندات المصدر / Source Documents",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم / User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Report",
                "ordering": ["-created_at"],
            },
        ),
    ]
