# Generated by Django 5.2.17 on 2026-09-24 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0027_agentrun_agentrunstep"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditWatchlistEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=200, verbose_name="اسم العميل"),
                ),
                (
                    "customer_key",
                    models.CharField(db_index=True, editable=False, max_length=200),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="السبب"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_watchlist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit Watchlist Entry",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "customer_key"),
                        name="uniq_credit_watchlist_user_customer",
                    )
                ],
            },
        ),
    ]
