# Generated by Django 5.2.17 on 2026-09-30 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0028_creditwatchlistentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesLead",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.CharField(max_length=200, verbose_name="المنتج")),
                (
                    "buyer_type",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="نوع المشتري",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="المدينة"
                    ),
                ),
                ("place_id", models.CharField(db_index=True, max_length=200)),
                ("business_name", models.CharField(max_length=300)),
                ("address", models.CharField(blank=True, default="", max_length=500)),
                ("phone", models.CharField(blank=True, default="", max_length=60)),
                ("website", models.URLField(blank=True, default="", max_length=500)),
                ("maps_url", models.URLField(blank=True, default="", max_length=500)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("reviews_count", models.PositiveIntegerField(default=0)),
                ("score", models.PositiveSmallIntegerField(db_index=True, default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جديد"),
                            ("contacted", "تم التواصل"),
                            ("negotiating", "قيد التفاوض"),
                            ("won", "تمت الصفقة"),
                            ("lost", "لم تتم"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=1000)),
                ("draft_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Lead",
                "ordering": ["-score", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "place_id", "product"),
                        name="uniq_sales_lead_user_place_product",
                    )
                ],
            },
        ),
    ]
